const Status = {
  UNREGISTERED: 'UNREGISTERED',
  REGISTERED: 'REGISTERED',
};

const MessageTypes = {
  REGISTER: 'REGISTER',
  REGISTER_METHOD: 'REGISTER_METHOD',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  SEND_MESSAGE: 'SEND_MESSAGE',
  CALLBACK: 'CALLBACK',
  RETURN: 'RETURN',
};

export { Status, MessageTypes };
